version: 2
jobs:
  build:
    working_directory: ~/app

    docker:
    - image: platanus/compose:1.22.0

    steps:
    - checkout
    - setup_remote_docker

    - run: docker info
  lint:
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout

      # Restore cache
      - restore_cache:
          keys:
          - linting-dependencies-bundle-{{ checksum "Gemfile.lock" }}
          - linting-dependencies-yarn-{{ checksum "yarn.lock" }}

      # Install ruby dependencies
      - run:
          name: Configure Bundler
          command: |
            gem install bundler:$(cat Gemfile.lock | tail -1 | tr -d " ")
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle --without "default production test" --with "development"

      # Cache bundle dependencies
      - save_cache:
          key: linting-dependencies-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Install node dependencies
      - run: yarn install

      # Cache yarn dependencies
      - save_cache:
          key: linting-dependencies-yarn-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: Install reviewdog
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin

      - run:
          name: Run reviewdog
          command: |
            files=$(git diff master --name-only)
            bundle exec rubocop $(echo $files) 2>&1 | ./bin/reviewdog -reporter=github-pr-review -f=rubocop
            npx eslint $(echo $files) 2>&1 | ./bin/reviewdog -reporter=github-pr-review -f=eslint

workflows:
  version: 2
  test_and_lint:
    jobs:
      - build
      - lint:
          context: org-global
