version: 2
jobs:
  test:
    working_directory: ~/app

    docker:
    - image: platanus/compose:1.22.0

    steps:
    - checkout
    - setup_remote_docker

    - run: docker info
  lint:
    docker:
      - image: circleci/ruby:2.6-node
    steps:
      - checkout

      # Restore cache
      - restore_cache:
          keys:
          - linting-dependencies-bundle-{{ checksum "Gemfile.lock" }}
          - linting-dependencies-yarn-{{ checksum "yarn.lock" }}

      # Install ruby dependencies
      - run:
          name: Configure Bundler
          command: |
            gem install bundler:$(cat Gemfile.lock | tail -1 | tr -d " ")
      - run: bundle install --jobs=4 --retry=3 --path vendor/bundle --without "default production test" --with "development"

      # Cache bundle dependencies
      - save_cache:
          key: linting-dependencies-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Install node dependencies
      - run: yarn install --frozen-lockfile

      # Cache yarn dependencies
      - save_cache:
          key: linting-dependencies-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Install reviewdog
          command: |
            curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh| sh -s -- -b ./bin

      - run:
          name: Run rubocop
          shell: /bin/bash
          command: |
            files=$(git diff origin/master --name-only)
            bundle exec rubocop $(echo $files) 2>&1 | ./bin/reviewdog -reporter=github-pr-review -f=rubocop

      - run:
          name: Run eslint
          shell: /bin/bash
          command: |
            files=$(git diff origin/master --name-only "*.js" "*.es6" "*.jsx" "*.vue")
            yarn run eslint $(echo $files) 2>&1 | ./bin/reviewdog -reporter=github-pr-review -f=eslint

      - run:
          name: Run stylelint
          shell: /bin/bash
          command: |
            files=$(git diff origin/master --name-only "*.scss" "*.css" "*.less")
            yarn run stylelint $(echo $files) 2>&1 | ./bin/reviewdog -reporter=github-pr-review -f=stylelint

      - run: git diff origin/master --name-only

      - run: yarn run eslint $(git diff origin/master --name-only)

      - run: yarn run stylelint $(git diff origin/master --name-only "*.scss" "*.css" "*.less")

workflows:
  version: 2
  test_and_lint:
    jobs:
      - test
      - lint:
          context: org-global
