name: Ateles

on: [pull_request]

jobs:
  pronto:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - run: echo "::set-env name=RUBY_VERSION::$(cat .ruby-version)"
    - run: echo "::set-env name=NODE_VERSION::$(cat .node-version)"
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ env.RUBY_VERSION }}
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}
    - uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/Ruby/
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - run: gem install bundler:$(cat Gemfile.lock | tail -1 | tr -d " ")
    - run: bundle install --without default production test
    - run: npm install --only=dev
    - run: $GEM_PATH
    - run: git fetch
    - run: PRONTO_PULL_REQUEST_ID="$(jq --raw-output .number "$GITHUB_EVENT_PATH")" PRONTO_GITHUB_ACCESS_TOKEN="${{ secrets.PRONTO_GITHUB_TOKEN }}" pronto run -f github_status github_pr -c origin/master
